In [24]:
# NB : This reload your library after each edit, 
# so you don't have to restart the kernel
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [25]:
import mlflow
import pandas as pd
import time
from diamonds.data import load_data, clean_data, create_X_y, split_data
from diamonds.model import create_model, create_preproc, train_model, evaluate_model, predict, preprocess_data, run_model, train_full_pipeline
from diamonds.predict import predict_values
import random
import plotly.express as px

In [ ]:
mlflow.set_tracking_uri("http://localhost:5000")
mlflow.set_experiment("diamonds")

In [26]:
df = load_data()
df

2026-03-12 14:37:27.052 | INFO     | diamonds.data:load_data:24 - Loading the data ...
2026-03-12 14:37:27.054 | INFO     | diamonds.data:load_data:35 - Data found in cache, loading from cache ...

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [27]:
df.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='object')

In [28]:
df_clean = clean_data(df)
len(df_clean)

2026-03-12 14:37:32.060 | INFO     | diamonds.data:clean_data:61 - Removed 20 rows with null values

53920

In [29]:
df = load_data()
df_clean = clean_data(df)
X, y = create_X_y(df_clean)
X_train, X_test, y_train, y_test = split_data(X, y)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

2026-03-12 14:37:33.541 | INFO     | diamonds.data:load_data:24 - Loading the data ...
2026-03-12 14:37:33.543 | INFO     | diamonds.data:load_data:35 - Data found in cache, loading from cache ...

2026-03-12 14:37:33.770 | INFO     | diamonds.data:clean_data:61 - Removed 20 rows with null values

(43136, 9) (10784, 9) (43136,) (10784,)

In [30]:
train_full_pipeline(X_train, y_train)

2026-03-12 14:37:35.553 | INFO     | diamonds.model:create_preproc:68 - Preprocessing pipeline created and fitted on the training data
2026-03-12 14:37:35.580 | INFO     | diamonds.model:create_model:40 - Creating a random forest regression model
2026-03-12 14:37:46.725 | INFO     | diamonds.model:train_model:96 - Time to train the model: 11.144 sec
2026-03-12 14:37:46.726 | INFO     | diamonds.model:train_full_pipeline:163 - Full pipeline created and trained
2026-03-12 14:37:46.993 | INFO     | diamonds.model:train_full_pipeline:165 - Full pipeline saved to local model registry

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('numeric',
                                                  Pipeline(steps=[('knn_imp',
                                                                   KNNImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0xf5c7112793d0>),
                                                 ('categorical',
                                                  Pipeline(steps=[('cat_imp',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('ohe',
                                                                   OneHotEncoder(drop='first',
                                                                                 sparse_output=False))]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0xf5c71127b5d0>)])),
                ('model',
                 RandomForestRegressor(max_depth=20, min_samples_leaf=2))])

In [8]:
preproc = create_preproc(X_train)
X_train_scaled = preprocess_data(preproc, X_train)
X_test_scaled = preprocess_data(preproc, X_test)
model_ = create_model("random_forest")
model_ = train_model(model_, X_train_scaled, y_train)
y_pred = predict(model_, X_test_scaled)
evaluate_model(y_test, y_pred)

2026-03-11 14:42:39.772 | INFO     | diamonds.model:create_preproc:68 - Preprocessing pipeline created and fitted on the training data
2026-03-11 14:42:39.808 | INFO     | diamonds.model:preprocess_data:17 - Data preprocessed using the preprocessing pipeline
2026-03-11 14:42:39.809 | INFO     | diamonds.model:preprocess_data:18 - Shape of the preprocessed data: (43136, 23) compared to the original data: (43136, 9)
2026-03-11 14:42:39.821 | INFO     | diamonds.model:preprocess_data:17 - Data preprocessed using the preprocessing pipeline
2026-03-11 14:42:39.822 | INFO     | diamonds.model:preprocess_data:18 - Shape of the preprocessed data: (10784, 23) compared to the original data: (10784, 9)
2026-03-11 14:42:39.823 | INFO     | diamonds.model:create_model:40 - Creating a random forest regression model
2026-03-11 14:42:51.035 | INFO     | diamonds.model:train_model:96 - Time to train the model: 11.212 sec
2026-03-11 14:42:51.198 | INFO     | diamonds.model:predict:129 - Predictions made using the trained model
2026-03-11 14:42:51.200 | INFO     | diamonds.model:evaluate_model:107 - Model evaluation completed
2026-03-11 14:42:51.201 | INFO     | diamonds.model:evaluate_model:108 - Model scores: {'mape': 0.07136887556472381, 'mae': 288.7961071326278, 'mse': 355442.80734121887, 'r2': 0.9778290982613651}

{'mape': 0.07136887556472381,
 'mae': 288.7961071326278,
 'mse': 355442.80734121887,
 'r2': 0.9778290982613651}

In [26]:

y_pred2 = predict(X_test_scaled)

dict_metrics = evaluate_model(y_test, y_pred)
for metric_name, metric_value in dict_metrics.items():
    mlflow.log_metric(metric_name, metric_value)

2026-03-11 14:55:58.486 | INFO     | diamonds.model:predict:18 - Model properly loaded from local model registry
2026-03-11 14:55:59.187 | INFO     | diamonds.model:predict:20 - Predictions made using the trained model
2026-03-11 14:55:59.209 | INFO     | diamonds.model:evaluate_model:107 - Model evaluation completed
2026-03-11 14:55:59.210 | INFO     | diamonds.model:evaluate_model:108 - Model scores: {'mape': 0.07136887556472381, 'mae': 288.7961071326278, 'mse': 355442.80734121887, 'r2': 0.9778290982613651}

In [14]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

mlflow.sklearn.autolog(max_tuning_runs=10)


params = {
    "n_estimators": [100],
    "max_depth": [20, 25, 30],
    "min_samples_split": [2, 5, 10],
    "min_samples_leaf": [2, 5, 10],
}
mlflow.end_run()
with mlflow.start_run(run_name="RF Hyperparameter Tuning"):
    model_ = RandomForestRegressor()
    grid_search = GridSearchCV(estimator=model_, param_grid=params, cv=5, n_jobs=-1, verbose=4)
    grid_search.fit(X_train_scaled, y_train)
    
    dict_metrics = evaluate_model(grid_search.best_estimator_, X_test_scaled, y_test)
    for metric_name, metric_value in dict_metrics.items():
        mlflow.log_metric(metric_name, metric_value)
    mlflow.log_param("best_params", grid_search.best_params_)

🏃 View run angry-calf-761 at: http://localhost:5000/#/experiments/1/runs/60c26c1b049e47c89f408c49f8ef54e6
🧪 View experiment at: http://localhost:5000/#/experiments/1
Fitting 5 folds for each of 27 candidates, totalling 135 fits
[CV 5/5] END max_depth=20, min_samples_leaf=2, min_samples_split=5, n_estimators=100;, score=0.974 total time=  10.6s
[CV 1/5] END max_depth=20, min_samples_leaf=2, min_samples_split=5, n_estimators=100;, score=0.973 total time=  10.7s
[CV 4/5] END max_depth=20, min_samples_leaf=2, min_samples_split=5, n_estimators=100;, score=0.973 total time=  10.7s
[CV 1/5] END max_depth=20, min_samples_leaf=2, min_samples_split=2, n_estimators=100;, score=0.973 total time=  10.9s
[CV 3/5] END max_depth=20, min_samples_leaf=2, min_samples_split=2, n_estimators=100;, score=0.972 total time=  11.0s
[CV 2/5] END max_depth=20, min_samples_leaf=2, min_samples_split=10, n_estimators=100;, score=0.974 total time=  10.9s
[CV 4/5] END max_depth=20, min_samples_leaf=2, min_samples_split=2, n_estimators=100;, score=0.973 total time=  11.1s
[CV 2/5] END max_depth=20, min_samples_leaf=2, min_samples_split=2, n_estimators=100;, score=0.975 total time=  11.1s
[CV 5/5] END max_depth=20, min_samples_leaf=2, min_samples_split=2, n_estimators=100;, score=0.974 total time=  11.2s
[CV 1/5] END max_depth=20, min_samples_leaf=2, min_samples_split=10, n_estimators=100;, score=0.973 total time=  11.2s
[CV 2/5] END max_depth=20, min_samples_leaf=2, min_samples_split=5, n_estimators=100;, score=0.974 total time=  11.7s
[CV 3/5] END max_depth=20, min_samples_leaf=2, min_samples_split=5, n_estimators=100;, score=0.972 total time=  11.7s
[CV 1/5] END max_depth=20, min_samples_leaf=5, min_samples_split=2, n_estimators=100;, score=0.972 total time=   9.6s
[CV 3/5] END max_depth=20, min_samples_leaf=2, min_samples_split=10, n_estimators=100;, score=0.971 total time=  10.0s
[CV 4/5] END max_depth=20, min_samples_leaf=2, min_samples_split=10, n_estimators=100;, score=0.972 total time=  10.1s
[CV 3/5] END max_depth=20, min_samples_leaf=5, min_samples_split=2, n_estimators=100;, score=0.970 total time=   9.7s
[CV 5/5] END max_depth=20, min_samples_leaf=2, min_samples_split=10, n_estimators=100;, score=0.973 total time=  10.1s
[CV 1/5] END max_depth=20, min_samples_leaf=5, min_samples_split=5, n_estimators=100;, score=0.971 total time=   9.8s
[CV 2/5] END max_depth=20, min_samples_leaf=5, min_samples_split=2, n_estimators=100;, score=0.972 total time=  10.0s
[CV 4/5] END max_depth=20, min_samples_leaf=5, min_samples_split=2, n_estimators=100;, score=0.970 total time=  10.0s
[CV 5/5] END max_depth=20, min_samples_leaf=5, min_samples_split=2, n_estimators=100;, score=0.971 total time=  10.2s
[CV 2/5] END max_depth=20, min_samples_leaf=5, min_samples_split=5, n_estimators=100;, score=0.972 total time=  10.6s
[CV 4/5] END max_depth=20, min_samples_leaf=5, min_samples_split=5, n_estimators=100;, score=0.971 total time=  10.4s
[CV 3/5] END max_depth=20, min_samples_leaf=5, min_samples_split=5, n_estimators=100;, score=0.969 total time=  10.6s
[CV 1/5] END max_depth=20, min_samples_leaf=10, min_samples_split=2, n_estimators=100;, score=0.968 total time=   9.5s
[CV 5/5] END max_depth=20, min_samples_leaf=5, min_samples_split=5, n_estimators=100;, score=0.970 total time=  10.4s
[CV 1/5] END max_depth=20, min_samples_leaf=5, min_samples_split=10, n_estimators=100;, score=0.971 total time=  10.3s
[CV 2/5] END max_depth=20, min_samples_leaf=10, min_samples_split=2, n_estimators=100;, score=0.969 total time=  10.0s
[CV 2/5] END max_depth=20, min_samples_leaf=5, min_samples_split=10, n_estimators=100;, score=0.972 total time=  10.4s
[CV 3/5] END max_depth=20, min_samples_leaf=5, min_samples_split=10, n_estimators=100;, score=0.969 total time=  10.4s
[CV 4/5] END max_depth=20, min_samples_leaf=5, min_samples_split=10, n_estimators=100;, score=0.971 total time=  10.5s
[CV 5/5] END max_depth=20, min_samples_leaf=5, min_samples_split=10, n_estimators=100;, score=0.971 total time=  10.7s
[CV 3/5] END max_depth=20, min_samples_leaf=10, min_samples_split=2, n_estimators=100;, score=0.966 total time=  10.6s
[CV 1/5] END max_depth=20, min_samples_leaf=10, min_samples_split=5, n_estimators=100;, score=0.968 total time=   9.5s
[CV 4/5] END max_depth=20, min_samples_leaf=10, min_samples_split=2, n_estimators=100;, score=0.967 total time=  10.4s
[CV 5/5] END max_depth=20, min_samples_leaf=10, min_samples_split=2, n_estimators=100;, score=0.967 total time=  10.5s
[CV 2/5] END max_depth=20, min_samples_leaf=10, min_samples_split=5, n_estimators=100;, score=0.969 total time=  10.0s
[CV 3/5] END max_depth=20, min_samples_leaf=10, min_samples_split=5, n_estimators=100;, score=0.966 total time=   9.9s
[CV 4/5] END max_depth=20, min_samples_leaf=10, min_samples_split=5, n_estimators=100;, score=0.968 total time=  10.0s
[CV 2/5] END max_depth=20, min_samples_leaf=10, min_samples_split=10, n_estimators=100;, score=0.969 total time=   9.8s
[CV 1/5] END max_depth=20, min_samples_leaf=10, min_samples_split=10, n_estimators=100;, score=0.968 total time=   9.8s
[CV 3/5] END max_depth=20, min_samples_leaf=10, min_samples_split=10, n_estimators=100;, score=0.966 total time=  10.2s
[CV 5/5] END max_depth=20, min_samples_leaf=10, min_samples_split=5, n_estimators=100;, score=0.967 total time=  10.6s
[CV 4/5] END max_depth=20, min_samples_leaf=10, min_samples_split=10, n_estimators=100;, score=0.968 total time=  10.0s
[CV 5/5] END max_depth=20, min_samples_leaf=10, min_samples_split=10, n_estimators=100;, score=0.966 total time=  10.3s
[CV 1/5] END max_depth=25, min_samples_leaf=2, min_samples_split=2, n_estimators=100;, score=0.973 total time=  13.2s
[CV 2/5] END max_depth=25, min_samples_leaf=2, min_samples_split=2, n_estimators=100;, score=0.975 total time=  13.9s
[CV 3/5] END max_depth=25, min_samples_leaf=2, min_samples_split=2, n_estimators=100;, score=0.972 total time=  14.1s
[CV 1/5] END max_depth=25, min_samples_leaf=2, min_samples_split=5, n_estimators=100;, score=0.973 total time=  13.1s
[CV 3/5] END max_depth=25, min_samples_leaf=2, min_samples_split=5, n_estimators=100;, score=0.972 total time=  13.3s
[CV 2/5] END max_depth=25, min_samples_leaf=2, min_samples_split=10, n_estimators=100;, score=0.974 total time=  12.2s
[CV 5/5] END max_depth=25, min_samples_leaf=2, min_samples_split=2, n_estimators=100;, score=0.974 total time=  13.6s
[CV 2/5] END max_depth=25, min_samples_leaf=2, min_samples_split=5, n_estimators=100;, score=0.975 total time=  13.5s
[CV 1/5] END max_depth=25, min_samples_leaf=2, min_samples_split=10, n_estimators=100;, score=0.973 total time=  12.8s
[CV 4/5] END max_depth=25, min_samples_leaf=2, min_samples_split=2, n_estimators=100;, score=0.973 total time=  14.1s
[CV 5/5] END max_depth=25, min_samples_leaf=2, min_samples_split=5, n_estimators=100;, score=0.973 total time=  13.3s
[CV 4/5] END max_depth=25, min_samples_leaf=2, min_samples_split=5, n_estimators=100;, score=0.973 total time=  13.4s
[CV 3/5] END max_depth=25, min_samples_leaf=2, min_samples_split=10, n_estimators=100;, score=0.971 total time=  12.6s
[CV 4/5] END max_depth=25, min_samples_leaf=2, min_samples_split=10, n_estimators=100;, score=0.973 total time=  13.0s
[CV 5/5] END max_depth=25, min_samples_leaf=2, min_samples_split=10, n_estimators=100;, score=0.973 total time=  13.2s
[CV 1/5] END max_depth=25, min_samples_leaf=5, min_samples_split=2, n_estimators=100;, score=0.971 total time=  11.8s
[CV 2/5] END max_depth=25, min_samples_leaf=5, min_samples_split=2, n_estimators=100;, score=0.972 total time=  11.9s
[CV 3/5] END max_depth=25, min_samples_leaf=5, min_samples_split=2, n_estimators=100;, score=0.970 total time=  11.8s
[CV 5/5] END max_depth=25, min_samples_leaf=5, min_samples_split=2, n_estimators=100;, score=0.971 total time=  11.8s
[CV 4/5] END max_depth=25, min_samples_leaf=5, min_samples_split=2, n_estimators=100;, score=0.971 total time=  11.9s
[CV 2/5] END max_depth=25, min_samples_leaf=5, min_samples_split=5, n_estimators=100;, score=0.972 total time=  11.7s
[CV 1/5] END max_depth=25, min_samples_leaf=5, min_samples_split=5, n_estimators=100;, score=0.971 total time=  11.9s
[CV 3/5] END max_depth=25, min_samples_leaf=5, min_samples_split=5, n_estimators=100;, score=0.970 total time=  11.8s
[CV 4/5] END max_depth=25, min_samples_leaf=5, min_samples_split=5, n_estimators=100;, score=0.971 total time=  12.2s
[CV 5/5] END max_depth=25, min_samples_leaf=5, min_samples_split=5, n_estimators=100;, score=0.971 total time=  12.1s
[CV 1/5] END max_depth=25, min_samples_leaf=5, min_samples_split=10, n_estimators=100;, score=0.971 total time=  12.0s
[CV 2/5] END max_depth=25, min_samples_leaf=5, min_samples_split=10, n_estimators=100;, score=0.972 total time=  12.2s
[CV 1/5] END max_depth=25, min_samples_leaf=10, min_samples_split=2, n_estimators=100;, score=0.969 total time=  10.6s
[CV 3/5] END max_depth=25, min_samples_leaf=10, min_samples_split=2, n_estimators=100;, score=0.966 total time=  10.8s
[CV 2/5] END max_depth=25, min_samples_leaf=10, min_samples_split=2, n_estimators=100;, score=0.969 total time=  11.0s
[CV 5/5] END max_depth=25, min_samples_leaf=10, min_samples_split=2, n_estimators=100;, score=0.966 total time=  10.8s
[CV 4/5] END max_depth=25, min_samples_leaf=10, min_samples_split=2, n_estimators=100;, score=0.968 total time=  11.1s
[CV 1/5] END max_depth=25, min_samples_leaf=10, min_samples_split=5, n_estimators=100;, score=0.968 total time=  10.6s
[CV 3/5] END max_depth=25, min_samples_leaf=5, min_samples_split=10, n_estimators=100;, score=0.969 total time=  12.0s
[CV 5/5] END max_depth=25, min_samples_leaf=5, min_samples_split=10, n_estimators=100;, score=0.971 total time=  12.0s
[CV 4/5] END max_depth=25, min_samples_leaf=5, min_samples_split=10, n_estimators=100;, score=0.970 total time=  12.3s
[CV 2/5] END max_depth=25, min_samples_leaf=10, min_samples_split=5, n_estimators=100;, score=0.969 total time=  11.2s
[CV 3/5] END max_depth=25, min_samples_leaf=10, min_samples_split=5, n_estimators=100;, score=0.967 total time=  11.3s
[CV 4/5] END max_depth=25, min_samples_leaf=10, min_samples_split=5, n_estimators=100;, score=0.968 total time=  11.7s
[CV 5/5] END max_depth=25, min_samples_leaf=10, min_samples_split=5, n_estimators=100;, score=0.966 total time=  11.9s
[CV 1/5] END max_depth=25, min_samples_leaf=10, min_samples_split=10, n_estimators=100;, score=0.968 total time=  12.3s
[CV 3/5] END max_depth=25, min_samples_leaf=10, min_samples_split=10, n_estimators=100;, score=0.966 total time=  12.1s
[CV 5/5] END max_depth=25, min_samples_leaf=10, min_samples_split=10, n_estimators=100;, score=0.966 total time=  12.1s
[CV 2/5] END max_depth=25, min_samples_leaf=10, min_samples_split=10, n_estimators=100;, score=0.969 total time=  12.5s
[CV 4/5] END max_depth=25, min_samples_leaf=10, min_samples_split=10, n_estimators=100;, score=0.968 total time=  12.3s
[CV 1/5] END max_depth=30, min_samples_leaf=2, min_samples_split=2, n_estimators=100;, score=0.973 total time=  15.9s
[CV 2/5] END max_depth=30, min_samples_leaf=2, min_samples_split=2, n_estimators=100;, score=0.975 total time=  16.7s
[CV 3/5] END max_depth=30, min_samples_leaf=2, min_samples_split=2, n_estimators=100;, score=0.972 total time=  17.1s
[CV 4/5] END max_depth=30, min_samples_leaf=2, min_samples_split=2, n_estimators=100;, score=0.973 total time=  18.5s
[CV 5/5] END max_depth=30, min_samples_leaf=2, min_samples_split=2, n_estimators=100;, score=0.974 total time=  17.0s
[CV 1/5] END max_depth=30, min_samples_leaf=2, min_samples_split=5, n_estimators=100;, score=0.973 total time=  16.9s
[CV 2/5] END max_depth=30, min_samples_leaf=2, min_samples_split=10, n_estimators=100;, score=0.974 total time=  15.6s
[CV 1/5] END max_depth=30, min_samples_leaf=2, min_samples_split=10, n_estimators=100;, score=0.973 total time=  16.2s
[CV 5/5] END max_depth=30, min_samples_leaf=2, min_samples_split=5, n_estimators=100;, score=0.974 total time=  16.4s
[CV 4/5] END max_depth=30, min_samples_leaf=2, min_samples_split=5, n_estimators=100;, score=0.973 total time=  16.5s
[CV 3/5] END max_depth=30, min_samples_leaf=2, min_samples_split=5, n_estimators=100;, score=0.972 total time=  17.1s
[CV 2/5] END max_depth=30, min_samples_leaf=2, min_samples_split=5, n_estimators=100;, score=0.975 total time=  17.9s
[CV 4/5] END max_depth=30, min_samples_leaf=2, min_samples_split=10, n_estimators=100;, score=0.973 total time=  14.3s
[CV 3/5] END max_depth=30, min_samples_leaf=2, min_samples_split=10, n_estimators=100;, score=0.971 total time=  15.6s
[CV 5/5] END max_depth=30, min_samples_leaf=2, min_samples_split=10, n_estimators=100;, score=0.973 total time=  13.9s
[CV 1/5] END max_depth=30, min_samples_leaf=5, min_samples_split=2, n_estimators=100;, score=0.971 total time=  12.1s
[CV 2/5] END max_depth=30, min_samples_leaf=5, min_samples_split=2, n_estimators=100;, score=0.972 total time=  12.6s
[CV 3/5] END max_depth=30, min_samples_leaf=5, min_samples_split=2, n_estimators=100;, score=0.969 total time=  13.5s
[CV 5/5] END max_depth=30, min_samples_leaf=5, min_samples_split=2, n_estimators=100;, score=0.971 total time=  12.3s
[CV 1/5] END max_depth=30, min_samples_leaf=5, min_samples_split=5, n_estimators=100;, score=0.971 total time=  12.3s
[CV 4/5] END max_depth=30, min_samples_leaf=5, min_samples_split=2, n_estimators=100;, score=0.971 total time=  13.4s
[CV 2/5] END max_depth=30, min_samples_leaf=5, min_samples_split=5, n_estimators=100;, score=0.972 total time=  13.2s
[CV 4/5] END max_depth=30, min_samples_leaf=5, min_samples_split=5, n_estimators=100;, score=0.971 total time=  13.0s
[CV 3/5] END max_depth=30, min_samples_leaf=5, min_samples_split=5, n_estimators=100;, score=0.970 total time=  13.7s
[CV 2/5] END max_depth=30, min_samples_leaf=5, min_samples_split=10, n_estimators=100;, score=0.972 total time=  13.3s
[CV 1/5] END max_depth=30, min_samples_leaf=5, min_samples_split=10, n_estimators=100;, score=0.971 total time=  13.5s
[CV 5/5] END max_depth=30, min_samples_leaf=5, min_samples_split=5, n_estimators=100;, score=0.971 total time=  14.2s
[CV 3/5] END max_depth=30, min_samples_leaf=5, min_samples_split=10, n_estimators=100;, score=0.970 total time=  14.4s
[CV 4/5] END max_depth=30, min_samples_leaf=5, min_samples_split=10, n_estimators=100;, score=0.971 total time=  14.1s
[CV 5/5] END max_depth=30, min_samples_leaf=5, min_samples_split=10, n_estimators=100;, score=0.971 total time=  14.2s
[CV 1/5] END max_depth=30, min_samples_leaf=10, min_samples_split=2, n_estimators=100;, score=0.968 total time=  11.9s
[CV 2/5] END max_depth=30, min_samples_leaf=10, min_samples_split=2, n_estimators=100;, score=0.969 total time=  12.0s
[CV 4/5] END max_depth=30, min_samples_leaf=10, min_samples_split=2, n_estimators=100;, score=0.968 total time=  11.5s
[CV 3/5] END max_depth=30, min_samples_leaf=10, min_samples_split=2, n_estimators=100;, score=0.966 total time=  12.0s
[CV 5/5] END max_depth=30, min_samples_leaf=10, min_samples_split=2, n_estimators=100;, score=0.967 total time=  11.8s
[CV 1/5] END max_depth=30, min_samples_leaf=10, min_samples_split=5, n_estimators=100;, score=0.968 total time=  11.7s
[CV 3/5] END max_depth=30, min_samples_leaf=10, min_samples_split=5, n_estimators=100;, score=0.966 total time=  11.6s
[CV 4/5] END max_depth=30, min_samples_leaf=10, min_samples_split=5, n_estimators=100;, score=0.968 total time=  11.0s
[CV 2/5] END max_depth=30, min_samples_leaf=10, min_samples_split=5, n_estimators=100;, score=0.969 total time=  11.8s
[CV 5/5] END max_depth=30, min_samples_leaf=10, min_samples_split=5, n_estimators=100;, score=0.966 total time=  10.3s
[CV 1/5] END max_depth=30, min_samples_leaf=10, min_samples_split=10, n_estimators=100;, score=0.968 total time=  10.2s
[CV 2/5] END max_depth=30, min_samples_leaf=10, min_samples_split=10, n_estimators=100;, score=0.969 total time=   9.8s
[CV 3/5] END max_depth=30, min_samples_leaf=10, min_samples_split=10, n_estimators=100;, score=0.966 total time=   9.6s
[CV 4/5] END max_depth=30, min_samples_leaf=10, min_samples_split=10, n_estimators=100;, score=0.968 total time=   9.4s
[CV 5/5] END max_depth=30, min_samples_leaf=10, min_samples_split=10, n_estimators=100;, score=0.966 total time=   9.3s

2026/03/10 14:40:30 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/03/10 14:40:47 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html
2026/03/10 14:41:03 INFO mlflow.sklearn.utils: Logging the 10 best runs, 17 runs will be omitted.

🏃 View run skillful-snipe-710 at: http://localhost:5000/#/experiments/1/runs/eba0886d47dc4a66807b89ea9150883c
🧪 View experiment at: http://localhost:5000/#/experiments/1
🏃 View run lyrical-fly-11 at: http://localhost:5000/#/experiments/1/runs/c6b6ab1082254c84b87439274b6dcfa1
🧪 View experiment at: http://localhost:5000/#/experiments/1
🏃 View run painted-midge-455 at: http://localhost:5000/#/experiments/1/runs/452b9306a8da4ab09541c61331c6eea3
🧪 View experiment at: http://localhost:5000/#/experiments/1
🏃 View run bemused-fly-2 at: http://localhost:5000/#/experiments/1/runs/3816edb81450467ea7a9f5c69a88ebed
🧪 View experiment at: http://localhost:5000/#/experiments/1
🏃 View run adaptable-fish-10 at: http://localhost:5000/#/experiments/1/runs/10ce09ad9e5144c79b4ecc20ea068d94
🧪 View experiment at: http://localhost:5000/#/experiments/1
🏃 View run indecisive-eel-169 at: http://localhost:5000/#/experiments/1/runs/dafc5e6d48214d6eb80781c999605d76
🧪 View experiment at: http://localhost:5000/#/experiments/1
🏃 View run secretive-boar-248 at: http://localhost:5000/#/experiments/1/runs/85678369a98041d58ceee1343f7248b8
🧪 View experiment at: http://localhost:5000/#/experiments/1
🏃 View run intrigued-cat-977 at: http://localhost:5000/#/experiments/1/runs/dd63b3439c0d4ca9a887d7216b9889db
🧪 View experiment at: http://localhost:5000/#/experiments/1
🏃 View run resilient-fowl-89 at: http://localhost:5000/#/experiments/1/runs/5438fc3f43a8442f976120403b8d4926
🧪 View experiment at: http://localhost:5000/#/experiments/1
🏃 View run legendary-rat-372 at: http://localhost:5000/#/experiments/1/runs/c89e470abd484ec2b74a9215ca36736b
🧪 View experiment at: http://localhost:5000/#/experiments/1

2026-03-10 14:41:04.953 | INFO     | diamonds.model:evaluate_model:104 - Model evaluation completed
2026-03-10 14:41:04.954 | INFO     | diamonds.model:evaluate_model:105 - Model scores: {'mape': 0.0715306975901693, 'mae': 289.85568212421225, 'mse': 356972.1098107043, 'r2': 0.977733707345923}

🏃 View run RF Hyperparameter Tuning at: http://localhost:5000/#/experiments/1/runs/11ab3f7bb72048d3a8b118a7542d91b1
🧪 View experiment at: http://localhost:5000/#/experiments/1

In [10]:
client = mlflow.MlflowClient()

model_name = "diamonds_model"
alias = "prod"


champion_version = mlflow.sklearn.load_model(f"models:/{model_name}@{alias}")

evaluate_model(champion_version, X_test_scaled, y_test)

2026-03-10 15:19:03.491 | INFO     | diamonds.model:evaluate_model:105 - Model evaluation completed
2026-03-10 15:19:03.492 | INFO     | diamonds.model:evaluate_model:106 - Model scores: {'mape': 0.07046109578637513, 'mae': 284.39159290131266, 'mse': 340921.04264397745, 'r2': 0.9787348997335694}

{'mape': 0.07046109578637513,
 'mae': 284.39159290131266,
 'mse': 340921.04264397745,
 'r2': 0.9787348997335694}

In [14]:
y_pred, scores = run_model(X_test_scaled, y_test)

2026-03-11 14:17:40.965 | INFO     | diamonds.model:run_model:4 - Model properly loaded from local model registry
2026-03-11 14:17:41.718 | INFO     | diamonds.model:predict:129 - Predictions made using the trained model
2026-03-11 14:17:41.720 | INFO     | diamonds.model:evaluate_model:107 - Model evaluation completed
2026-03-11 14:17:41.721 | INFO     | diamonds.model:evaluate_model:108 - Model scores: {'mape': 0.07393215478710555, 'mae': 298.4364881859249, 'mse': 386601.4320363179, 'r2': 0.9758855653155349}
2026-03-11 14:17:41.908 | INFO     | diamonds.model:run_model:9 - Model evaluation scores logged to mlflow

In [7]:
dict_predict = {}
list_index = random.sample(range(len(df_clean)), 100)
for idx in list_index:
    start = time.perf_counter()
    X_df = df_clean.drop(columns=["price"], axis=1).copy()
    test_X = pd.DataFrame([X_df.iloc[idx]])
    test_y = df_clean.iloc[idx]["price"]
    pred = predict_values(test_X)
    total_time = time.perf_counter() - start
    dict_predict[idx] = {"True value": test_y, "Predicted value": pred[0], "difference": abs(test_y - pred[0]), "relative error": abs(test_y - pred[0])/test_y, "total_time": total_time}

    #print(f"True value: {test_y}, Predicted value: {pred:.2f}, difference = {abs(test_y - pred)[0]:.2f}, relative error = {abs(test_y - pred)[0]/test_y:.2%}")

2026-03-11 15:31:54.447 | INFO     | diamonds.predict:predict_values:13 - Model loaded successfully for prediction
2026-03-11 15:31:54.454 | INFO     | diamonds.model:preprocess_data:88 - Data preprocessed using the preprocessing pipeline
2026-03-11 15:31:54.455 | INFO     | diamonds.model:preprocess_data:89 - Shape of the preprocessed data: (1, 23) compared to the original data: (1, 9)
2026-03-11 15:31:54.456 | INFO     | diamonds.predict:predict_values:15 - Data preprocessed successfully for prediction
2026-03-11 15:31:54.801 | INFO     | diamonds.model:predict:128 - Model properly loaded from local model registry
2026-03-11 15:31:54.831 | INFO     | diamonds.model:predict:130 - Predictions made using the trained model
2026-03-11 15:31:54.851 | INFO     | diamonds.predict:predict_values:18 - Predictions made for prediction function
2026-03-11 15:31:55.041 | INFO     | diamonds.predict:predict_values:13 - Model loaded successfully for prediction
2026-03-11 15:31:55.049 | INFO     | diamonds.model:preprocess_data:88 - Data preprocessed using the preprocessing pipeline
2026-03-11 15:31:55.049 | INFO     | diamonds.model:preprocess_data:89 - Shape of the preprocessed data: (1, 23) compared to the original data: (1, 9)
2026-03-11 15:31:55.050 | INFO     | diamonds.predict:predict_values:15 - Data preprocessed successfully for prediction
2026-03-11 15:31:55.195 | INFO     | diamonds.model:predict:128 - Model properly loaded from local model registry
2026-03-11 15:31:55.229 | INFO     | diamonds.model:predict:130 - Predictions made using the trained model
2026-03-11 15:31:55.248 | INFO     | diamonds.predict:predict_values:18 - Predictions made for prediction function
2026-03-11 15:31:55.507 | INFO     | diamonds.predict:predict_values:13 - Model loaded successfully for prediction
2026-03-11 15:31:55.514 | INFO     | diamonds.model:preprocess_data:88 - Data preprocessed using the preprocessing pipeline
2026-03-11 15:31:55.515 | INFO     | diamonds.model:preprocess_data:89 - Shape of the preprocessed data: (1, 23) compared to the original data: (1, 9)
2026-03-11 15:31:55.515 | INFO     | diamonds.predict:predict_values:15 - Data preprocessed successfully for prediction
2026-03-11 15:31:55.662 | INFO     | diamonds.model:predict:128 - Model properly loaded from local model registry
2026-03-11 15:31:55.694 | INFO     | diamonds.model:predict:130 - Predictions made using the trained model
2026-03-11 15:31:55.714 | INFO     | diamonds.predict:predict_values:18 - Predictions made for prediction function
2026-03-11 15:31:55.966 | INFO     | diamonds.predict:predict_values:13 - Model loaded successfully for prediction
2026-03-11 15:31:55.971 | INFO     | diamonds.model:preprocess_data:88 - Data preprocessed using the preprocessing pipeline
2026-03-11 15:31:55.972 | INFO     | diamonds.model:preprocess_data:89 - Shape of the preprocessed data: (1, 23) compared to the original data: (1, 9)
2026-03-11 15:31:55.972 | INFO     | diamonds.predict:predict_values:15 - Data preprocessed successfully for prediction
2026-03-11 15:31:56.118 | INFO     | diamonds.model:predict:128 - Model properly loaded from local model registry
2026-03-11 15:31:56.143 | INFO     | diamonds.model:predict:130 - Predictions made using the trained model
2026-03-11 15:31:56.163 | INFO     | diamonds.predict:predict_values:18 - Predictions made for prediction function
2026-03-11 15:31:56.420 | INFO     | diamonds.predict:predict_values:13 - Model loaded successfully for prediction
2026-03-11 15:31:56.425 | INFO     | diamonds.model:preprocess_data:88 - Data preprocessed using the preprocessing pipeline
2026-03-11 15:31:56.426 | INFO     | diamonds.model:preprocess_data:89 - Shape of the preprocessed data: (1, 23) compared to the original data: (1, 9)
2026-03-11 15:31:56.426 | INFO     | diamonds.predict:predict_values:15 - Data preprocessed successfully for prediction
2026-03-11 15:31:56.569 | INFO     | diamonds.model:predict:128 - Model properly loaded from local model registry
2026-03-11 15:31:56.593 | INFO     | diamonds.model:predict:130 - Predictions made using the trained model
2026-03-11 15:31:56.612 | INFO     | diamonds.predict:predict_values:18 - Predictions made for prediction function
2026-03-11 15:31:56.866 | INFO     | diamonds.predict:predict_values:13 - Model loaded successfully for prediction
2026-03-11 15:31:56.871 | INFO     | diamonds.model:preprocess_data:88 - Data preprocessed using the preprocessing pipeline
2026-03-11 15:31:56.871 | INFO     | diamonds.model:preprocess_data:89 - Shape of the preprocessed data: (1, 23) compared to the original data: (1, 9)
2026-03-11 15:31:56.872 | INFO     | diamonds.predict:predict_values:15 - Data preprocessed successfully for prediction
2026-03-11 15:31:57.016 | INFO     | diamonds.model:predict:128 - Model properly loaded from local model registry
2026-03-11 15:31:57.049 | INFO     | diamonds.model:predict:130 - Predictions made using the trained model
2026-03-11 15:31:57.068 | INFO     | diamonds.predict:predict_values:18 - Predictions made for prediction function
2026-03-11 15:31:57.329 | INFO     | diamonds.predict:predict_values:13 - Model loaded successfully for prediction
2026-03-11 15:31:57.335 | INFO     | diamonds.model:preprocess_data:88 - Data preprocessed using the preprocessing pipeline
2026-03-11 15:31:57.336 | INFO     | diamonds.model:preprocess_data:89 - Shape of the preprocessed data: (1, 23) compared to the original data: (1, 9)
2026-03-11 15:31:57.336 | INFO     | diamonds.predict:predict_values:15 - Data preprocessed successfully for prediction
2026-03-11 15:31:57.486 | INFO     | diamonds.model:predict:128 - Model properly loaded from local model registry
2026-03-11 15:31:57.509 | INFO     | diamonds.model:predict:130 - Predictions made using the trained model
2026-03-11 15:31:57.529 | INFO     | diamonds.predict:predict_values:18 - Predictions made for prediction function
2026-03-11 15:31:57.641 | INFO     | diamonds.predict:predict_values:13 - Model loaded successfully for prediction
2026-03-11 15:31:57.646 | INFO     | diamonds.model:preprocess_data:88 - Data preprocessed using the preprocessing pipeline
2026-03-11 15:31:57.647 | INFO     | diamonds.model:preprocess_data:89 - Shape of the preprocessed data: (1, 23) compared to the original data: (1, 9)
2026-03-11 15:31:57.648 | INFO     | diamonds.predict:predict_values:15 - Data preprocessed successfully for prediction
2026-03-11 15:31:57.790 | INFO     | diamonds.model:predict:128 - Model properly loaded from local model registry
2026-03-11 15:31:57.814 | INFO     | diamonds.model:predict:130 - Predictions made using the trained model
2026-03-11 15:31:57.833 | INFO     | diamonds.predict:predict_values:18 - Predictions made for prediction function
2026-03-11 15:31:57.921 | INFO     | diamonds.predict:predict_values:13 - Model loaded successfully for prediction
2026-03-11 15:31:57.927 | INFO     | diamonds.model:preprocess_data:88 - Data preprocessed using the preprocessing pipeline
2026-03-11 15:31:57.927 | INFO     | diamonds.model:preprocess_data:89 - Shape of the preprocessed data: (1, 23) compared to the original data: (1, 9)
2026-03-11 15:31:57.928 | INFO     | diamonds.predict:predict_values:15 - Data preprocessed successfully for prediction
2026-03-11 15:31:58.067 | INFO     | diamonds.model:predict:128 - Model properly loaded from local model registry
2026-03-11 15:31:58.093 | INFO     | diamonds.model:predict:130 - Predictions made using the trained model
2026-03-11 15:31:58.113 | INFO     | diamonds.predict:predict_values:18 - Predictions made for prediction function
2026-03-11 15:31:58.374 | INFO     | diamonds.predict:predict_values:13 - Model loaded successfully for prediction
2026-03-11 15:31:58.382 | INFO     | diamonds.model:preprocess_data:88 - Data preprocessed using the preprocessing pipeline
2026-03-11 15:31:58.383 | INFO     | diamonds.model:preprocess_data:89 - Shape of the preprocessed data: (1, 23) compared to the original data: (1, 9)
2026-03-11 15:31:58.384 | INFO     | diamonds.predict:predict_values:15 - Data preprocessed successfully for prediction
2026-03-11 15:31:58.523 | INFO     | diamonds.model:predict:128 - Model properly loaded from local model registry
2026-03-11 15:31:58.557 | INFO     | diamonds.model:predict:130 - Predictions made using the trained model
2026-03-11 15:31:58.578 | INFO     | diamonds.predict:predict_values:18 - Predictions made for prediction function
2026-03-11 15:31:59.178 | INFO     | diamonds.predict:predict_values:13 - Model loaded successfully for prediction
2026-03-11 15:31:59.185 | INFO     | diamonds.model:preprocess_data:88 - Data preprocessed using the preprocessing pipeline
2026-03-11 15:31:59.185 | INFO     | diamonds.model:preprocess_data:89 - Shape of the preprocessed data: (1, 23) compared to the original data: (1, 9)
2026-03-11 15:31:59.186 | INFO     | diamonds.predict:predict_values:15 - Data preprocessed successfully for prediction
2026-03-11 15:31:59.526 | INFO     | diamonds.model:predict:128 - Model properly loaded from local model registry
2026-03-11 15:31:59.551 | INFO     | diamonds.model:predict:130 - Predictions made using the trained model
2026-03-11 15:31:59.571 | INFO     | diamonds.predict:predict_values:18 - Predictions made for prediction function
2026-03-11 15:31:59.834 | INFO     | diamonds.predict:predict_values:13 - Model loaded successfully for prediction
2026-03-11 15:31:59.839 | INFO     | diamonds.model:preprocess_data:88 - Data preprocessed using the preprocessing pipeline
2026-03-11 15:31:59.839 | INFO     | diamonds.model:preprocess_data:89 - Shape of the preprocessed data: (1, 23) compared to the original data: (1, 9)
2026-03-11 15:31:59.840 | INFO     | diamonds.predict:predict_values:15 - Data preprocessed successfully for prediction
2026-03-11 15:32:00.011 | INFO     | diamonds.model:predict:128 - Model properly loaded from local model registry
2026-03-11 15:32:00.044 | INFO     | diamonds.model:predict:130 - Predictions made using the trained model
2026-03-11 15:32:00.066 | INFO     | diamonds.predict:predict_values:18 - Predictions made for prediction function
2026-03-11 15:32:00.232 | INFO     | diamonds.predict:predict_values:13 - Model loaded successfully for prediction
2026-03-11 15:32:00.238 | INFO     | diamonds.model:preprocess_data:88 - Data preprocessed using the preprocessing pipeline
2026-03-11 15:32:00.239 | INFO     | diamonds.model:preprocess_data:89 - Shape of the preprocessed data: (1, 23) compared to the original data: (1, 9)
2026-03-11 15:32:00.240 | INFO     | diamonds.predict:predict_values:15 - Data preprocessed successfully for prediction
2026-03-11 15:32:00.427 | INFO     | diamonds.model:predict:128 - Model properly loaded from local model registry
2026-03-11 15:32:00.455 | INFO     | diamonds.model:predict:130 - Predictions made using the trained model
2026-03-11 15:32:00.474 | INFO     | diamonds.predict:predict_values:18 - Predictions made for prediction function
2026-03-11 15:32:00.593 | INFO     | diamonds.predict:predict_values:13 - Model loaded successfully for prediction
2026-03-11 15:32:00.600 | INFO     | diamonds.model:preprocess_data:88 - Data preprocessed using the preprocessing pipeline
2026-03-11 15:32:00.601 | INFO     | diamonds.model:preprocess_data:89 - Shape of the preprocessed data: (1, 23) compared to the original data: (1, 9)
2026-03-11 15:32:00.601 | INFO     | diamonds.predict:predict_values:15 - Data preprocessed successfully for prediction
2026-03-11 15:32:00.747 | INFO     | diamonds.model:predict:128 - Model properly loaded from local model registry
2026-03-11 15:32:00.773 | INFO     | diamonds.model:predict:130 - Predictions made using the trained model
2026-03-11 15:32:00.793 | INFO     | diamonds.predict:predict_values:18 - Predictions made for prediction function
2026-03-11 15:32:00.905 | INFO     | diamonds.predict:predict_values:13 - Model loaded successfully for prediction
2026-03-11 15:32:00.910 | INFO     | diamonds.model:preprocess_data:88 - Data preprocessed using the preprocessing pipeline
2026-03-11 15:32:00.911 | INFO     | diamonds.model:preprocess_data:89 - Shape of the preprocessed data: (1, 23) compared to the original data: (1, 9)
2026-03-11 15:32:00.912 | INFO     | diamonds.predict:predict_values:15 - Data preprocessed successfully for prediction
2026-03-11 15:32:01.282 | INFO     | diamonds.model:predict:128 - Model properly loaded from local model registry
2026-03-11 15:32:01.308 | INFO     | diamonds.model:predict:130 - Predictions made using the trained model
2026-03-11 15:32:01.332 | INFO     | diamonds.predict:predict_values:18 - Predictions made for prediction function
2026-03-11 15:32:01.425 | INFO     | diamonds.predict:predict_values:13 - Model loaded successfully for prediction
2026-03-11 15:32:01.432 | INFO     | diamonds.model:preprocess_data:88 - Data preprocessed using the preprocessing pipeline
2026-03-11 15:32:01.433 | INFO     | diamonds.model:preprocess_data:89 - Shape of the preprocessed data: (1, 23) compared to the original data: (1, 9)
2026-03-11 15:32:01.434 | INFO     | diamonds.predict:predict_values:15 - Data preprocessed successfully for prediction
2026-03-11 15:32:01.575 | INFO     | diamonds.model:predict:128 - Model properly loaded from local model registry
2026-03-11 15:32:01.599 | INFO     | diamonds.model:predict:130 - Predictions made using the trained model
2026-03-11 15:32:01.619 | INFO     | diamonds.predict:predict_values:18 - Predictions made for prediction function
2026-03-11 15:32:01.886 | INFO     | diamonds.predict:predict_values:13 - Model loaded successfully for prediction
2026-03-11 15:32:01.892 | INFO     | diamonds.model:preprocess_data:88 - Data preprocessed using the preprocessing pipeline
2026-03-11 15:32:01.892 | INFO     | diamonds.model:preprocess_data:89 - Shape of the preprocessed data: (1, 23) compared to the original data: (1, 9)
2026-03-11 15:32:01.892 | INFO     | diamonds.predict:predict_values:15 - Data preprocessed successfully for prediction
2026-03-11 15:32:02.039 | INFO     | diamonds.model:predict:128 - Model properly loaded from local model registry
2026-03-11 15:32:02.066 | INFO     | diamonds.model:predict:130 - Predictions made using the trained model
2026-03-11 15:32:02.085 | INFO     | diamonds.predict:predict_values:18 - Predictions made for prediction function
2026-03-11 15:32:02.331 | INFO     | diamonds.predict:predict_values:13 - Model loaded successfully for prediction
2026-03-11 15:32:02.336 | INFO     | diamonds.model:preprocess_data:88 - Data preprocessed using the preprocessing pipeline
2026-03-11 15:32:02.337 | INFO     | diamonds.model:preprocess_data:89 - Shape of the preprocessed data: (1, 23) compared to the original data: (1, 9)
2026-03-11 15:32:02.337 | INFO     | diamonds.predict:predict_values:15 - Data preprocessed successfully for prediction
2026-03-11 15:32:02.479 | INFO     | diamonds.model:predict:128 - Model properly loaded from local model registry
2026-03-11 15:32:02.514 | INFO     | diamonds.model:predict:130 - Predictions made using the trained model
2026-03-11 15:32:02.534 | INFO     | diamonds.predict:predict_values:18 - Predictions made for prediction function
2026-03-11 15:32:02.634 | INFO     | diamonds.predict:predict_values:13 - Model loaded successfully for prediction
2026-03-11 15:32:02.639 | INFO     | diamonds.model:preprocess_data:88 - Data preprocessed using the preprocessing pipeline
2026-03-11 15:32:02.640 | INFO     | diamonds.model:preprocess_data:89 - Shape of the preprocessed data: (1, 23) compared to the original data: (1, 9)
2026-03-11 15:32:02.640 | INFO     | diamonds.predict:predict_values:15 - Data preprocessed successfully for prediction
2026-03-11 15:32:02.785 | INFO     | diamonds.model:predict:128 - Model properly loaded from local model registry
2026-03-11 15:32:02.812 | INFO     | diamonds.model:predict:130 - Predictions made using the trained model
2026-03-11 15:32:02.832 | INFO     | diamonds.predict:predict_values:18 - Predictions made for prediction function
2026-03-11 15:32:02.957 | INFO     | diamonds.predict:predict_values:13 - Model loaded successfully for prediction
2026-03-11 15:32:02.964 | INFO     | diamonds.model:preprocess_data:88 - Data preprocessed using the preprocessing pipeline
2026-03-11 15:32:02.965 | INFO     | diamonds.model:preprocess_data:89 - Shape of the preprocessed data: (1, 23) compared to the original data: (1, 9)
2026-03-11 15:32:02.965 | INFO     | diamonds.predict:predict_values:15 - Data preprocessed successfully for prediction
2026-03-11 15:32:03.106 | INFO     | diamonds.model:predict:128 - Model properly loaded from local model registry
2026-03-11 15:32:03.131 | INFO     | diamonds.model:predict:130 - Predictions made using the trained model
2026-03-11 15:32:03.150 | INFO     | diamonds.predict:predict_values:18 - Predictions made for prediction function
2026-03-11 15:32:03.249 | INFO     | diamonds.predict:predict_values:13 - Model loaded successfully for prediction
2026-03-11 15:32:03.255 | INFO     | diamonds.model:preprocess_data:88 - Data preprocessed using the preprocessing pipeline
2026-03-11 15:32:03.255 | INFO     | diamonds.model:preprocess_data:89 - Shape of the preprocessed data: (1, 23) compared to the original data: (1, 9)
2026-03-11 15:32:03.255 | INFO     | diamonds.predict:predict_values:15 - Data preprocessed successfully for prediction
2026-03-11 15:32:03.510 | INFO     | diamonds.model:predict:128 - Model properly loaded from local model registry
2026-03-11 15:32:03.537 | INFO     | diamonds.model:predict:130 - Predictions made using the trained model
2026-03-11 15:32:03.557 | INFO     | diamonds.predict:predict_values:18 - Predictions made for prediction function
2026-03-11 15:32:03.814 | INFO     | diamonds.predict:predict_values:13 - Model loaded successfully for prediction
2026-03-11 15:32:03.820 | INFO     | diamonds.model:preprocess_data:88 - Data preprocessed using the preprocessing pipeline
2026-03-11 15:32:03.821 | INFO     | diamonds.model:preprocess_data:89 - Shape of the preprocessed data: (1, 23) compared to the original data: (1, 9)
2026-03-11 15:32:03.821 | INFO     | diamonds.predict:predict_values:15 - Data preprocessed successfully for prediction
2026-03-11 15:32:03.973 | INFO     | diamonds.model:predict:128 - Model properly loaded from local model registry
2026-03-11 15:32:04.003 | INFO     | diamonds.model:predict:130 - Predictions made using the trained model
2026-03-11 15:32:04.023 | INFO     | diamonds.predict:predict_values:18 - Predictions made for prediction function
2026-03-11 15:32:04.116 | INFO     | diamonds.predict:predict_values:13 - Model loaded successfully for prediction
2026-03-11 15:32:04.121 | INFO     | diamonds.model:preprocess_data:88 - Data preprocessed using the preprocessing pipeline
2026-03-11 15:32:04.122 | INFO     | diamonds.model:preprocess_data:89 - Shape of the preprocessed data: (1, 23) compared to the original data: (1, 9)
2026-03-11 15:32:04.123 | INFO     | diamonds.predict:predict_values:15 - Data preprocessed successfully for prediction
2026-03-11 15:32:04.262 | INFO     | diamonds.model:predict:128 - Model properly loaded from local model registry
2026-03-11 15:32:04.285 | INFO     | diamonds.model:predict:130 - Predictions made using the trained model
2026-03-11 15:32:04.305 | INFO     | diamonds.predict:predict_values:18 - Predictions made for prediction function
2026-03-11 15:32:04.422 | INFO     | diamonds.predict:predict_values:13 - Model loaded successfully for prediction
2026-03-11 15:32:04.427 | INFO     | diamonds.model:preprocess_data:88 - Data preprocessed using the preprocessing pipeline
2026-03-11 15:32:04.428 | INFO     | diamonds.model:preprocess_data:89 - Shape of the preprocessed data: (1, 23) compared to the original data: (1, 9)
2026-03-11 15:32:04.429 | INFO     | diamonds.predict:predict_values:15 - Data preprocessed successfully for prediction

In [8]:
predict_df = pd.DataFrame.from_dict(dict_predict, orient="index")
predict_df.head()

       True value  Predicted value  difference  relative error  total_time
43119        1388      1393.809045    5.809045        0.004185    1.138126
12603        5290      5159.995983  130.004017        0.024575    0.419320
21034         625       623.331524    1.668476        0.002670    0.463517
48285         533       559.968217   26.968217        0.050597    0.453101
51226        2354      2412.580357   58.580357        0.024885    0.445923

In [9]:
px.histogram(predict_df, x=predict_df["relative error"]*50, 
             nbins=100, 
             width=800, height=500,
             title="Relative Error Distribution between the predicted value and the true value")

In [10]:
px.scatter(predict_df, x=predict_df["True value"], y=predict_df["relative error"]*100,
              width=800, height=500, title="Predicted vs True Values")

In [11]:
px.histogram(predict_df, x="total_time", 
             nbins=50, 
             width=800, height=500,
             title="Total Time Distribution to get the answer back from the model")